language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
    - "pip install --upgrade pip"
    - "pip install flake8 pytest-cov '.[tests]'"
    
# command to run tests
script: "py.test --cov=algorithms -vv tests/"

after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - python:
      - nightly
